language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get build-dep -qq python-scipy python-numpy
 - sudo apt-get install -qq python-matplotlib
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
 - pip install numpy --use-mirrors
 - pip install scipy --use-mirrors
 - pip install nose --use-mirrors
# command to run tests, e.g. python setup.py test
script: nosetests pydelsigma/*.py
